# Generated by Django 5.1.4 on 2025-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Eventtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventtype', models.CharField(max_length=30)),
            ],
        ),
    ]
