# Generated by Django 5.1.4 on 2025-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Packagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_type', models.CharField(max_length=30)),
            ],
        ),
    ]
