# Generated by Django 5.1.4 on 2025-02-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_tbl_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Addevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_poster', models.FileField(upload_to='Assets/Servicer/photo/')),
                ('event_description', models.CharField(max_length=30)),
                ('event_count', models.CharField(max_length=30)),
                ('event_status', models.CharField(max_length=30)),
                ('event_startdate', models.CharField(max_length=30)),
                ('event_enddate', models.CharField(max_length=30)),
                ('event_amount', models.CharField(max_length=30)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_organization')),
            ],
        ),
    ]
