# Generated by Django 5.1.4 on 2025-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_addevent',
            name='event_status',
            field=models.IntegerField(default=0),
        ),
    ]
