# Generated by Django 5.1.4 on 2025-02-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('Guest', '0005_tbl_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Addpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=30)),
                ('pack_description', models.CharField(max_length=30)),
                ('pack_amount', models.CharField(max_length=30)),
                ('pack_photo', models.FileField(upload_to='Assets/Servicer/photo/')),
                ('pack_spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('pack_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_packagetype')),
            ],
        ),
    ]
