# Generated by Django 5.1.4 on 2025-02-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_organization'),
        ('Serviceprovider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=30)),
                ('work_description', models.CharField(max_length=100)),
                ('work_photo', models.FileField(upload_to='Assets/ServiceProvider/Work/')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/ServiceProvider/Gallery/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviceprovider.tbl_work')),
            ],
        ),
    ]
