# Generated by Django 5.1.4 on 2025-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_Name', models.CharField(max_length=30)),
                ('sp_Gmail', models.CharField(max_length=30)),
                ('sp_Contact', models.CharField(max_length=30)),
                ('sp_Address', models.CharField(max_length=30)),
                ('sp_Place_id', models.CharField(max_length=30)),
                ('sp_Password', models.CharField(max_length=30)),
                ('sp_Photo', models.FileField(upload_to='Assets/Servicer/photo/')),
                ('sp_Proof', models.FileField(upload_to='Assets/Servicer/photo/')),
                ('sp_Status', models.IntegerField(default=0)),
            ],
        ),
    ]
