# Generated by Django 5.1.4 on 2025-02-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_place'),
        ('Guest', '0002_delete_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_Name', models.CharField(max_length=30)),
                ('sp_Gmail', models.CharField(max_length=30)),
                ('sp_Contact', models.CharField(max_length=30)),
                ('sp_Address', models.CharField(max_length=30)),
                ('sp_Password', models.CharField(max_length=30)),
                ('sp_Photo', models.FileField(upload_to='Assets/Servicer/photo/')),
                ('sp_Proof', models.FileField(upload_to='Assets/Servicer/proof/')),
                ('sp_Status', models.IntegerField(default=0)),
                ('sp_Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
