# Generated by Django 5.1.4 on 2025-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=30)),
                ('user_Email', models.CharField(max_length=30)),
                ('user_Contact', models.CharField(max_length=30)),
                ('user_Address', models.CharField(max_length=30)),
                ('user_Password', models.CharField(max_length=30)),
            ],
        ),
    ]
