# Generated by Django 5.1.4 on 2025-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_Name', models.CharField(max_length=30)),
                ('org_Email', models.CharField(max_length=30)),
                ('org_Contact', models.CharField(max_length=30)),
                ('org_Address', models.CharField(max_length=30)),
                ('org_Place', models.CharField(max_length=30)),
                ('org_Logo', models.FileField(upload_to='Assets/Organization/logo/')),
                ('org_Proof', models.FileField(upload_to='Assets/Organization/proof/')),
                ('org_Password', models.CharField(max_length=30)),
                ('org_Status', models.IntegerField(default=0)),
            ],
        ),
    ]
