# Generated by Django 5.1.4 on 2025-03-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('Guest', '0005_tbl_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_organization',
            name='org_Place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
