# Generated by Django 5.1.4 on 2025-03-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('Guest', '0006_alter_tbl_organization_org_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_organization',
            name='org_Place',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
            preserve_default=False,
        ),
    ]
