# Generated by Django 5.1.4 on 2025-02-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('Guest', '0005_tbl_organization'),
        ('Organization', '0001_initial'),
        ('Serviceprovider', '0002_tbl_work_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.CharField(max_length=30)),
                ('Booking_todate', models.CharField(max_length=30)),
                ('Booking_description', models.CharField(max_length=30)),
                ('Booking_amount', models.CharField(max_length=30)),
                ('Booking_status', models.CharField(max_length=30)),
                ('Eventtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_eventtype')),
                ('Place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_status', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviceprovider.tbl_addpackage')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventbooking_count', models.CharField(max_length=30)),
                ('Eventbooking_amount', models.CharField(max_length=30)),
                ('Eventbooking_status', models.CharField(max_length=30)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.tbl_addevent')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
