# Generated by Django 5.1.4 on 2025-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='Booking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='Cart_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_eventbooking',
            name='Eventbooking_status',
            field=models.IntegerField(default=0),
        ),
    ]
