# Generated by Django 5.1.4 on 2025-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='Booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='Booking_todate',
            field=models.DateField(),
        ),
    ]
