# Generated by Django 5.1.4 on 2025-02-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('User', '0003_alter_tbl_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='Booking_todate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='Eventtype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_eventtype'),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='Place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
