# Generated by Django 5.1.4 on 2025-02-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_booking_booking_todate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='Package',
        ),
        migrations.DeleteModel(
            name='tbl_Booking',
        ),
        migrations.DeleteModel(
            name='tbl_Cart',
        ),
    ]
