# Generated by Django 5.1.4 on 2025-02-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_packagetype'),
        ('Guest', '0005_tbl_organization'),
        ('Serviceprovider', '0002_tbl_work_tbl_gallery'),
        ('User', '0005_remove_tbl_cart_booking_remove_tbl_cart_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField(auto_now_add=True)),
                ('Booking_todate', models.DateField(null=True)),
                ('Booking_description', models.CharField(max_length=30)),
                ('Booking_amount', models.CharField(max_length=30)),
                ('Booking_status', models.IntegerField(default=0)),
                ('Packagetype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_packagetype')),
                ('Place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_status', models.IntegerField(default=0)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviceprovider.tbl_addpackage')),
            ],
        ),
    ]
