# Generated by Django 5.1.4 on 2025-03-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_organization_org_place'),
        ('User', '0009_remove_tbl_booking_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_title', models.CharField(max_length=30)),
                ('Complaint_content', models.CharField(max_length=30)),
                ('Complaint_date', models.DateField(auto_now_add=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_reply', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('Custombooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_custombooking')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_content', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('Custombooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_custombooking')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_review', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_organization')),
                ('servicerprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
