# Generated by Django 5.1.7 on 2025-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_delete_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_content', models.CharField(max_length=30)),
            ],
        ),
    ]
