# Generated by Django 5.1.7 on 2025-03-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Feedback',
        ),
    ]
