# Generated by Django 5.1.7 on 2025-03-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
