# Generated by Django 5.1.7 on 2025-03-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_organization_org_place'),
        ('User', '0015_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_title', models.CharField(max_length=30)),
                ('Complaint_content', models.CharField(max_length=30)),
                ('Complaint_date', models.DateField(auto_now_add=True)),
                ('Complaint_status', models.IntegerField(default=0)),
                ('Complaint_reply', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('Custombooking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_custombooking')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
