# Generated by Django 5.1.7 on 2025-03-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceprovider', '0002_tbl_work_tbl_gallery'),
        ('User', '0016_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='Booking',
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Serviceprovider.tbl_addpackage'),
        ),
    ]
